web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
mysql:
    image: mysql
    container_name: dykyi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root 
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306 
    ports:
      - "3306:3306"
    expose:    
      - "3306"
adminer:
    image: adminer
    container_name: dykyi-adminer
    restart: always
    links:
      - mysql
    ports:
      - 8888:8080

# mongo:
#    image: mongo
#    container_name: dykyi-mongo
#    ports:
#      - 27017:27017 # Проброс портов для внешнего доступа
#    volumes:
#      - ./database/mongo:/data/db
#  postgres:
#    image: postgres:latest
#    container_name: dykyi-postgres
#    ports:
#      - 5432:5432 # Проброс портов для внешнего доступа
#    volumes:
#      - ./database/postgres:/data/postgres
#    environment:
#      POSTGRES_PASSWORD: secret
#      POSTGRES_USER: postgres
#      PGDATA: /data/postgres
#  mysql:
#    image: mysql
#    container_name: dykyi-mysql
#    restart: always
#    volumes:
#      - ./data:/docker-entrypoint-initdb.d
#      - ./database/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: root 
#      MYSQL_PASSWORD: root
#      MYSQL_PORT: 3306 
#    ports:
#      - "3306:3306"
#    expose:    
#      - "3306"
#  vault:
#    image: vault
#    privileged: true
#    ports:
#      - "8200:8200"
#    cap_add:
#      - ALL
#    environment:
#      VAULT_ADDR: http://127.0.0.1:8200
#      VAULT_DEV_ROOT_TOKEN_ID: myroot
#      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:1234
#  redis:
#    image: redis:latest
#  elasticsearch:
#    image: elasticsearch:2.4.1

