version: "2"
services:
  nginx:
    image: nocaut2012/nginx:nginx
# dockerfile: ./Dockerfile
# build: ./contaners/nginx
    ports:
      - 80:80
    volumes:
      - ./logs:/etc/logs/nginx
      - ./contaners/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - fpm:rw
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: nginx -g "daemon off;" # Можно было указать в докер-фале, но можно и здесь)
    links:
      - fpm
  fpm:
    image: nocaut2012/php7
# dockerfile: ./Dockerfile
# build: ./contaners/fpm
    volumes:
      - ./php-code:/var/www:rw
    links:
      - mysql
  adminer:
    image: adminer
    container_name: dykyi-adminer
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8888:8080
#  mongo:
#    image: mongo
#    container_name: dykyi-mongo
#    ports:
#      - 27017:27017 # Проброс портов для внешнего доступа
#    volumes:
#      - ./database/mongo:/data/db
#  postgres:
#    image: postgres:latest
#    container_name: dykyi-postgres
#    ports:
#      - 5432:5432 # Проброс портов для внешнего доступа
#    volumes:
#      - ./database/postgres:/data/postgres
#    environment:
#      POSTGRES_PASSWORD: secret
#      POSTGRES_USER: postgres
#      PGDATA: /data/postgres
  mysql:
    image: mysql
    container_name: dykyi-mysql
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./database/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306 
    ports:
      - "3306:3306"
    expose:    
      - "3306"
