web:
    image: nginx:latest
    ports:
        - "8080:80"
        - "443:443"
    expose: 
        - "443"
    volumes:
        - ./code:/code
        - ./ssl:/etc/nginx/ssl
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
