nginx:
 image: nocaut2012/nginx:nginx
# dockerfile: ./Dockerfile
# build: ./contaners/nginx
 ports:
  - 80:80
 volumes:
  - ./logs:/etc/logs/nginx
  - ./contaners/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
 volumes_from:
  - fpm:rw
 environment:
  - NGINX_HOST=localhost
  - NGINX_PORT=80
 command: nginx -g "daemon off;" # Можно было указать в докер-фале, но можно и здесь)
 links:
  - fpm
fpm:
 image: nocaut2012/php7:php7-fpm
# dockerfile: ./Dockerfile
# build: ./contaners/fpm
 volumes:
  - ./php-code:/var/www:rw
 links:
  - mongo
  - postgres
  - mysql
adminer:
 image: adminer
 restart: always
 ports:
  - 8888:8080
mongo:
 image: mongo
 ports:
  - 27017:27017 # Проброс портов для внешнего доступа 
 volumes:
 - ./database/mongo:/data/db
postgres:
 image: postgres:latest
 ports:
  - 5432:5432 # Проброс портов для внешнего доступа 
 volumes:
  - ./database/postgres:/data/postgres
 environment:
  POSTGRES_PASSWORD: secret
  POSTGRES_USER: postgres
  PGDATA : /data/postgres
mysql:
 image: mysql
 restart: always
 volumes:
  - ./database/mysql:/var/lib/mysql 
 environment:
  MYSQL_ROOT_PASSWORD: root
 expose:    
  - "3306"

